services:
  image-classification-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TFHUB_CACHE_DIR=/tmp/tfhub
    volumes:
      - tfhub_cache:/tmp/tfhub
    restart: unless-stopped

volumes:
  tfhub_cache: